///**
// * NOTE: This class is auto generated by the swagger code generator program (unset).
// * https://github.com/swagger-api/swagger-codegen
// * Do not edit the class manually.
// */
//package io.swagger.api;
//
//import io.swagger.model.PaymentType;
//import io.swagger.model.RefundType;
//import io.swagger.annotations.*;
//import org.springframework.http.ResponseEntity;
//import org.springframework.validation.annotation.Validated;
//import org.springframework.web.bind.annotation.PathVariable;
//import org.springframework.web.bind.annotation.RequestBody;
//import org.springframework.web.bind.annotation.RequestHeader;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestMethod;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.RequestPart;
//import org.springframework.web.multipart.MultipartFile;
//
//import javax.validation.Valid;
//import javax.validation.constraints.*;
//import java.util.List;
//@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-12-22T13:14:44.496+03:00")
//
//@Api(value = "account", description = "the account API")
//public interface AccountApi {
//
//    @ApiOperation(value = "Retrieve a payment of an account", nickname = "retrieveAccountPayments", notes = "", response = PaymentType.class, responseContainer = "List", tags={ "payments of an account", })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "Payments retrieved successfully", response = PaymentType.class, responseContainer = "List") })
//    @RequestMapping(value = "/account/{accountId}/payment",
//        produces = { "application/json" },
//        method = RequestMethod.GET)
//    ResponseEntity<List<PaymentType>> retrieveAccountPayments(@ApiParam(value = "ID of the account whose payment needs to be fetched",required=true) @PathVariable("accountId") String accountId);
//
//
//    @ApiOperation(value = "Retrieve refunds of an account", nickname = "retrieveAccountRefunds", notes = "", response = RefundType.class, responseContainer = "List", tags={ "refunds of an account", })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "Refunds retrieved successfully", response = RefundType.class, responseContainer = "List") })
//    @RequestMapping(value = "/account/{accountId}/refund",
//        produces = { "application/json" },
//        method = RequestMethod.GET)
//    ResponseEntity<List<RefundType>> retrieveAccountRefunds(@ApiParam(value = "ID of the account whose refund needs to be fetched",required=true) @PathVariable("accountId") String accountId);
//
//}
